spring:
  application:
    name: intelligence-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
debug: false

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

eureka:
  client:
    register-with-eureka: true   # register this service
    fetch-registry: true         # fetch other services
    service-url:
      defaultZone: http://localhost:8761/eureka/