# k8s/services/config-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: lovable-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: praj031/distributed-lovable-config-service:latest #GKE has caching issues, using latest tag to ensure it always pulls the new image
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s #Tells all config clients to use k8s profile only when they fetch config from config server, this way we can have different configs for local and k8s environment
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GIT_USERNAME
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GIT_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 90 #Time delay before the first probe is initiated, giving the config server enough time to start up and be ready to serve requests
            periodSeconds: 15 #Actuator health check
            timeoutSeconds: 5 #Time to wait for the health check response before considering it a failure
            failureThreshold: 3 #Number of consecutive failures before marking the pod as unhealthy and stopping traffic to it
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: lovable-core
spec:
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888